import type { Referral } from '@/lib/types';

// Helper to generate dates relative to today
function daysAgo(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
}

function hoursAgo(hours: number): string {
  const date = new Date();
  date.setHours(date.getHours() - hours);
  return date.toISOString();
}

function daysFromNow(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
}

// Central Florida area codes
const areaCodes = ['407', '321', '352'];

// Generate phone number
function phone(index: number): string {
  const areaCode = areaCodes[index % areaCodes.length];
  const prefix = String(555 + (index % 10)).padStart(3, '0');
  const suffix = String(1000 + index).slice(-4);
  return `(${areaCode}) ${prefix}-${suffix}`;
}

// Sources for referrals
const sources = ['Facebook', 'Google', 'Instagram', 'Website', 'Referral'];

// 85 referrals covering all scenarios
export const mockReferrals: Referral[] = [
  // ========================================
  // SCENARIO 1: SUCCESS STORIES - signed_icf (15 referrals)
  // ========================================
  {
    id: 'ref-001',
    firstName: 'Maria',
    lastName: 'Santos',
    email: 'maria.santos@gmail.com',
    phone: phone(1),
    dateOfBirth: '1968-03-15',
    submittedAt: daysAgo(21),
    source: 'Facebook',
    studyId: 'study-001',
    status: 'signed_icf',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(13),
    appointmentDate: null,
    notes: [
      {
        id: 'note-001',
        referralId: 'ref-001',
        authorId: 'user-001',
        authorName: 'Sarah Chen',
        content: 'Patient very interested, husband also has T2D',
        createdAt: daysAgo(20),
      },
      {
        id: 'note-002',
        referralId: 'ref-001',
        authorId: 'user-001',
        authorName: 'Sarah Chen',
        content: 'Prefers morning appointments. Spanish speaker - comfortable in English.',
        createdAt: daysAgo(19),
      },
    ],
    messages: [
      {
        id: 'msg-001',
        referralId: 'ref-001',
        direction: 'outbound',
        content: 'Hi Maria, this is Sarah from Orlando Clinical Research. Thank you for your interest in the AURORA diabetes study!',
        sentAt: daysAgo(20),
        status: 'delivered',
      },
      {
        id: 'msg-002',
        referralId: 'ref-001',
        direction: 'inbound',
        content: "Hi! Yes I'm still interested. What times work?",
        sentAt: daysAgo(20),
        status: 'read',
      },
    ],
    createdAt: daysAgo(21),
    updatedAt: daysAgo(13),
  },
  {
    id: 'ref-009',
    firstName: 'William',
    lastName: 'Johnson',
    email: 'wjohnson@gmail.com',
    phone: phone(9),
    dateOfBirth: '1965-08-22',
    submittedAt: daysAgo(28),
    source: 'Google',
    studyId: 'study-001',
    status: 'signed_icf',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(14),
    appointmentDate: null,
    notes: [{ id: 'note-009', referralId: 'ref-009', authorId: 'user-001', authorName: 'Sarah Chen', content: 'Excellent candidate, very engaged in study', createdAt: daysAgo(14) }],
    messages: [],
    createdAt: daysAgo(28),
    updatedAt: daysAgo(14),
  },
  {
    id: 'ref-010',
    firstName: 'Barbara',
    lastName: 'Williams',
    email: 'bwilliams@yahoo.com',
    phone: phone(10),
    dateOfBirth: '1970-02-14',
    submittedAt: daysAgo(25),
    source: 'Facebook',
    studyId: 'study-003',
    status: 'signed_icf',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(11),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(25),
    updatedAt: daysAgo(11),
  },
  {
    id: 'ref-011',
    firstName: 'Charles',
    lastName: 'Brown',
    email: 'cbrown@outlook.com',
    phone: phone(11),
    dateOfBirth: '1958-11-30',
    submittedAt: daysAgo(30),
    source: 'Referral',
    studyId: 'study-001',
    status: 'signed_icf',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(16),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(30),
    updatedAt: daysAgo(16),
  },
  {
    id: 'ref-012',
    firstName: 'Margaret',
    lastName: 'Jones',
    email: 'mjones@gmail.com',
    phone: phone(12),
    dateOfBirth: '1962-07-08',
    submittedAt: daysAgo(22),
    source: 'Google',
    studyId: 'study-003',
    status: 'signed_icf',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(10),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(22),
    updatedAt: daysAgo(10),
  },
  {
    id: 'ref-013',
    firstName: 'Joseph',
    lastName: 'Garcia',
    email: 'jgarcia@gmail.com',
    phone: phone(13),
    dateOfBirth: '1967-04-25',
    submittedAt: daysAgo(19),
    source: 'Instagram',
    studyId: 'study-001',
    status: 'signed_icf',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(8),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(19),
    updatedAt: daysAgo(8),
  },
  {
    id: 'ref-014',
    firstName: 'Dorothy',
    lastName: 'Miller',
    email: 'dmiller@aol.com',
    phone: phone(14),
    dateOfBirth: '1955-09-18',
    submittedAt: daysAgo(26),
    source: 'Facebook',
    studyId: 'study-002',
    status: 'signed_icf',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(12),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(26),
    updatedAt: daysAgo(12),
  },
  {
    id: 'ref-060',
    firstName: 'Kenneth',
    lastName: 'Adams',
    email: 'kadams@gmail.com',
    phone: phone(60),
    dateOfBirth: '1963-05-12',
    submittedAt: daysAgo(24),
    source: 'Google',
    studyId: 'study-001',
    status: 'signed_icf',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(9),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(24),
    updatedAt: daysAgo(9),
  },
  {
    id: 'ref-061',
    firstName: 'Betty',
    lastName: 'Nelson',
    email: 'bnelson@yahoo.com',
    phone: phone(61),
    dateOfBirth: '1960-10-03',
    submittedAt: daysAgo(27),
    source: 'Referral',
    studyId: 'study-003',
    status: 'signed_icf',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(13),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(27),
    updatedAt: daysAgo(13),
  },
  {
    id: 'ref-062',
    firstName: 'Ronald',
    lastName: 'Carter',
    email: 'rcarter@outlook.com',
    phone: phone(62),
    dateOfBirth: '1957-12-20',
    submittedAt: daysAgo(29),
    source: 'Website',
    studyId: 'study-001',
    status: 'signed_icf',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(15),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(29),
    updatedAt: daysAgo(15),
  },
  {
    id: 'ref-063',
    firstName: 'Sandra',
    lastName: 'Roberts',
    email: 'sroberts@gmail.com',
    phone: phone(63),
    dateOfBirth: '1969-01-28',
    submittedAt: daysAgo(23),
    source: 'Facebook',
    studyId: 'study-003',
    status: 'signed_icf',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(10),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(23),
    updatedAt: daysAgo(10),
  },
  {
    id: 'ref-064',
    firstName: 'Donald',
    lastName: 'Turner',
    email: 'dturner@gmail.com',
    phone: phone(64),
    dateOfBirth: '1964-06-15',
    submittedAt: daysAgo(20),
    source: 'Google',
    studyId: 'study-001',
    status: 'signed_icf',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(7),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(20),
    updatedAt: daysAgo(7),
  },
  {
    id: 'ref-065',
    firstName: 'Ashley',
    lastName: 'Phillips',
    email: 'aphillips@yahoo.com',
    phone: phone(65),
    dateOfBirth: '1972-08-09',
    submittedAt: daysAgo(18),
    source: 'Instagram',
    studyId: 'study-004',
    status: 'signed_icf',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(6),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(18),
    updatedAt: daysAgo(6),
  },
  {
    id: 'ref-066',
    firstName: 'Gary',
    lastName: 'Campbell',
    email: 'gcampbell@gmail.com',
    phone: phone(66),
    dateOfBirth: '1959-03-22',
    submittedAt: daysAgo(25),
    source: 'Referral',
    studyId: 'study-001',
    status: 'signed_icf',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(11),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(25),
    updatedAt: daysAgo(11),
  },

  // ========================================
  // SCENARIO 2: HOT LEADS - new (10 referrals)
  // ========================================
  {
    id: 'ref-002',
    firstName: 'James',
    lastName: 'Thompson',
    email: 'jthompson@yahoo.com',
    phone: phone(2),
    dateOfBirth: '1975-07-22',
    submittedAt: hoursAgo(3),
    source: 'Google',
    studyId: 'study-001',
    status: 'new',
    assignedTo: null,
    lastContactedAt: null,
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
  },
  {
    id: 'ref-003',
    firstName: 'Linda',
    lastName: 'Washington',
    email: 'linda.w@gmail.com',
    phone: phone(3),
    dateOfBirth: '1962-11-08',
    submittedAt: hoursAgo(18),
    source: 'Facebook',
    studyId: 'study-002',
    status: 'new',
    assignedTo: 'user-001',
    lastContactedAt: null,
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: hoursAgo(18),
    updatedAt: hoursAgo(18),
  },
  {
    id: 'ref-067',
    firstName: 'Jessica',
    lastName: 'Evans',
    email: 'jevans@gmail.com',
    phone: phone(67),
    dateOfBirth: '1978-04-11',
    submittedAt: hoursAgo(2),
    source: 'Instagram',
    studyId: 'study-001',
    status: 'new',
    assignedTo: null,
    lastContactedAt: null,
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
  },
  {
    id: 'ref-068',
    firstName: 'Daniel',
    lastName: 'Edwards',
    email: 'dedwards@yahoo.com',
    phone: phone(68),
    dateOfBirth: '1966-09-25',
    submittedAt: hoursAgo(5),
    source: 'Google',
    studyId: 'study-003',
    status: 'new',
    assignedTo: null,
    lastContactedAt: null,
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
  },
  {
    id: 'ref-069',
    firstName: 'Michelle',
    lastName: 'Collins',
    email: 'mcollins@outlook.com',
    phone: phone(69),
    dateOfBirth: '1971-12-03',
    submittedAt: hoursAgo(8),
    source: 'Facebook',
    studyId: 'study-004',
    status: 'new',
    assignedTo: null,
    lastContactedAt: null,
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(8),
  },
  {
    id: 'ref-070',
    firstName: 'Christopher',
    lastName: 'Stewart',
    email: 'cstewart@gmail.com',
    phone: phone(70),
    dateOfBirth: '1963-07-17',
    submittedAt: hoursAgo(12),
    source: 'Website',
    studyId: 'study-001',
    status: 'new',
    assignedTo: 'user-002',
    lastContactedAt: null,
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(12),
  },
  {
    id: 'ref-071',
    firstName: 'Amanda',
    lastName: 'Sanchez',
    email: 'asanchez@gmail.com',
    phone: phone(71),
    dateOfBirth: '1975-02-28',
    submittedAt: hoursAgo(20),
    source: 'Referral',
    studyId: 'study-002',
    status: 'new',
    assignedTo: 'user-001',
    lastContactedAt: null,
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: hoursAgo(20),
    updatedAt: hoursAgo(20),
  },
  {
    id: 'ref-072',
    firstName: 'Matthew',
    lastName: 'Morris',
    email: 'mmorris@yahoo.com',
    phone: phone(72),
    dateOfBirth: '1968-11-14',
    submittedAt: hoursAgo(26),
    source: 'Google',
    studyId: 'study-001',
    status: 'new',
    assignedTo: null,
    lastContactedAt: null,
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: hoursAgo(26),
    updatedAt: hoursAgo(26),
  },
  {
    id: 'ref-073',
    firstName: 'Stephanie',
    lastName: 'Rogers',
    email: 'srogers@gmail.com',
    phone: phone(73),
    dateOfBirth: '1973-06-05',
    submittedAt: hoursAgo(30),
    source: 'Facebook',
    studyId: 'study-003',
    status: 'new',
    assignedTo: 'user-003',
    lastContactedAt: null,
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: hoursAgo(30),
    updatedAt: hoursAgo(30),
  },
  {
    id: 'ref-074',
    firstName: 'Andrew',
    lastName: 'Reed',
    email: 'areed@outlook.com',
    phone: phone(74),
    dateOfBirth: '1960-08-21',
    submittedAt: hoursAgo(36),
    source: 'Instagram',
    studyId: 'study-004',
    status: 'new',
    assignedTo: null,
    lastContactedAt: null,
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: hoursAgo(36),
    updatedAt: hoursAgo(36),
  },

  // ========================================
  // SCENARIO 3: ATTEMPT STATUSES (29 total)
  // ========================================
  // attempt_1 (8 referrals)
  {
    id: 'ref-016',
    firstName: 'Kevin',
    lastName: 'Anderson',
    email: 'kanderson@gmail.com',
    phone: phone(16),
    dateOfBirth: '1972-03-10',
    submittedAt: daysAgo(3),
    source: 'Google',
    studyId: 'study-001',
    status: 'attempt_1',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(2),
    appointmentDate: null,
    notes: [{ id: 'note-016', referralId: 'ref-016', authorId: 'user-001', authorName: 'Sarah Chen', content: 'LVM, will try again tomorrow', createdAt: daysAgo(2) }],
    messages: [],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
  {
    id: 'ref-017',
    firstName: 'Laura',
    lastName: 'Taylor',
    email: 'ltaylor@yahoo.com',
    phone: phone(17),
    dateOfBirth: '1965-09-28',
    submittedAt: daysAgo(4),
    source: 'Facebook',
    studyId: 'study-002',
    status: 'attempt_1',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(3),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(3),
  },
  {
    id: 'ref-018',
    firstName: 'Brian',
    lastName: 'Thomas',
    email: 'bthomas@outlook.com',
    phone: phone(18),
    dateOfBirth: '1970-06-15',
    submittedAt: daysAgo(2),
    source: 'Instagram',
    studyId: 'study-003',
    status: 'attempt_1',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(1),
    appointmentDate: null,
    notes: [{ id: 'note-018', referralId: 'ref-018', authorId: 'user-003', authorName: 'Jennifer Park', content: 'Phone rang, no answer', createdAt: daysAgo(1) }],
    messages: [],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: 'ref-019',
    firstName: 'Emily',
    lastName: 'Jackson',
    email: 'ejackson@gmail.com',
    phone: phone(19),
    dateOfBirth: '1968-12-02',
    submittedAt: daysAgo(3),
    source: 'Website',
    studyId: 'study-001',
    status: 'attempt_1',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(2),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
  {
    id: 'ref-020',
    firstName: 'Timothy',
    lastName: 'White',
    email: 'twhite@aol.com',
    phone: phone(20),
    dateOfBirth: '1975-04-20',
    submittedAt: daysAgo(4),
    source: 'Referral',
    studyId: 'study-004',
    status: 'attempt_1',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(3),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(3),
  },
  {
    id: 'ref-021',
    firstName: 'Nicole',
    lastName: 'Harris',
    email: 'nharris@gmail.com',
    phone: phone(21),
    dateOfBirth: '1967-08-08',
    submittedAt: daysAgo(2),
    source: 'Google',
    studyId: 'study-001',
    status: 'attempt_1',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(1),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: 'ref-075',
    firstName: 'Joshua',
    lastName: 'Cook',
    email: 'jcook@gmail.com',
    phone: phone(75),
    dateOfBirth: '1971-05-30',
    submittedAt: daysAgo(3),
    source: 'Facebook',
    studyId: 'study-002',
    status: 'attempt_1',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(2),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
  {
    id: 'ref-076',
    firstName: 'Heather',
    lastName: 'Morgan',
    email: 'hmorgan@yahoo.com',
    phone: phone(76),
    dateOfBirth: '1964-10-14',
    submittedAt: daysAgo(4),
    source: 'Website',
    studyId: 'study-003',
    status: 'attempt_1',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(3),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(3),
  },

  // attempt_2 (7 referrals)
  {
    id: 'ref-022',
    firstName: 'Thomas',
    lastName: 'Wright',
    email: 'twright@gmail.com',
    phone: phone(22),
    dateOfBirth: '1960-01-25',
    submittedAt: daysAgo(6),
    source: 'Facebook',
    studyId: 'study-002',
    status: 'attempt_2',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(3),
    appointmentDate: null,
    notes: [{ id: 'note-022', referralId: 'ref-022', authorId: 'user-002', authorName: 'Mike Rodriguez', content: 'Spoke briefly, at work. Call back after 5pm', createdAt: daysAgo(3) }],
    messages: [],
    createdAt: daysAgo(6),
    updatedAt: daysAgo(3),
  },
  {
    id: 'ref-023',
    firstName: 'Jennifer',
    lastName: 'Lopez',
    email: 'jlopez@outlook.com',
    phone: phone(23),
    dateOfBirth: '1974-07-12',
    submittedAt: daysAgo(5),
    source: 'Google',
    studyId: 'study-001',
    status: 'attempt_2',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(2),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },
  {
    id: 'ref-024',
    firstName: 'Ryan',
    lastName: 'Hill',
    email: 'rhill@gmail.com',
    phone: phone(24),
    dateOfBirth: '1969-11-18',
    submittedAt: daysAgo(7),
    source: 'Instagram',
    studyId: 'study-003',
    status: 'attempt_2',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(4),
    appointmentDate: null,
    notes: [{ id: 'note-024', referralId: 'ref-024', authorId: 'user-003', authorName: 'Jennifer Park', content: 'Interested but traveling. Follow up next Monday', createdAt: daysAgo(4) }],
    messages: [],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(4),
  },
  {
    id: 'ref-025',
    firstName: 'Elizabeth',
    lastName: 'Scott',
    email: 'escott@yahoo.com',
    phone: phone(25),
    dateOfBirth: '1966-04-05',
    submittedAt: daysAgo(6),
    source: 'Referral',
    studyId: 'study-001',
    status: 'attempt_2',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(3),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(6),
    updatedAt: daysAgo(3),
  },
  {
    id: 'ref-026',
    firstName: 'Jason',
    lastName: 'Green',
    email: 'jgreen@gmail.com',
    phone: phone(26),
    dateOfBirth: '1973-08-30',
    submittedAt: daysAgo(5),
    source: 'Website',
    studyId: 'study-004',
    status: 'attempt_2',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(2),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },
  {
    id: 'ref-077',
    firstName: 'Rachel',
    lastName: 'Bell',
    email: 'rbell@outlook.com',
    phone: phone(77),
    dateOfBirth: '1968-02-19',
    submittedAt: daysAgo(6),
    source: 'Google',
    studyId: 'study-002',
    status: 'attempt_2',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(3),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(6),
    updatedAt: daysAgo(3),
  },
  {
    id: 'ref-078',
    firstName: 'Aaron',
    lastName: 'Murphy',
    email: 'amurphy@gmail.com',
    phone: phone(78),
    dateOfBirth: '1970-09-07',
    submittedAt: daysAgo(7),
    source: 'Facebook',
    studyId: 'study-001',
    status: 'attempt_2',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(4),
    appointmentDate: null,
    notes: [{ id: 'note-078', referralId: 'ref-078', authorId: 'user-001', authorName: 'Sarah Chen', content: 'Asked to call back tomorrow morning', createdAt: daysAgo(4) }],
    messages: [],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(4),
  },

  // attempt_3 (5 referrals)
  {
    id: 'ref-027',
    firstName: 'Kimberly',
    lastName: 'Baker',
    email: 'kbaker@aol.com',
    phone: phone(27),
    dateOfBirth: '1963-05-22',
    submittedAt: daysAgo(9),
    source: 'Facebook',
    studyId: 'study-001',
    status: 'attempt_3',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(4),
    appointmentDate: null,
    notes: [{ id: 'note-027', referralId: 'ref-027', authorId: 'user-001', authorName: 'Sarah Chen', content: 'LVM x2, sent SMS', createdAt: daysAgo(4) }],
    messages: [],
    createdAt: daysAgo(9),
    updatedAt: daysAgo(4),
  },
  {
    id: 'ref-028',
    firstName: 'Karen',
    lastName: 'Mitchell',
    email: 'kmitchell@gmail.com',
    phone: phone(28),
    dateOfBirth: '1971-10-15',
    submittedAt: daysAgo(8),
    source: 'Google',
    studyId: 'study-001',
    status: 'attempt_3',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(3),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(8),
    updatedAt: daysAgo(3),
  },
  {
    id: 'ref-029',
    firstName: 'Mark',
    lastName: 'Perez',
    email: 'mperez@yahoo.com',
    phone: phone(29),
    dateOfBirth: '1967-02-08',
    submittedAt: daysAgo(10),
    source: 'Instagram',
    studyId: 'study-003',
    status: 'attempt_3',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(5),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(5),
  },
  {
    id: 'ref-079',
    firstName: 'Lisa',
    lastName: 'Bailey',
    email: 'lbailey@gmail.com',
    phone: phone(79),
    dateOfBirth: '1965-07-26',
    submittedAt: daysAgo(9),
    source: 'Referral',
    studyId: 'study-002',
    status: 'attempt_3',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(4),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(9),
    updatedAt: daysAgo(4),
  },
  {
    id: 'ref-080',
    firstName: 'Edward',
    lastName: 'Rivera',
    email: 'erivera@outlook.com',
    phone: phone(80),
    dateOfBirth: '1969-12-11',
    submittedAt: daysAgo(8),
    source: 'Website',
    studyId: 'study-004',
    status: 'attempt_3',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(3),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(8),
    updatedAt: daysAgo(3),
  },

  // attempt_4 (4 referrals)
  {
    id: 'ref-005',
    firstName: 'Patricia',
    lastName: 'Davis',
    email: 'pdavis@aol.com',
    phone: phone(5),
    dateOfBirth: '1965-09-12',
    submittedAt: daysAgo(14),
    source: 'Google',
    studyId: 'study-001',
    status: 'attempt_4',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(3),
    appointmentDate: null,
    notes: [{ id: 'note-005', referralId: 'ref-005', authorId: 'user-001', authorName: 'Sarah Chen', content: 'LVM x3. Sent 2 SMS, no response. Trying one more time then marking inactive.', createdAt: daysAgo(3) }],
    messages: [{ id: 'msg-005', referralId: 'ref-005', direction: 'outbound', content: 'Hi Patricia, following up about the diabetes study.', sentAt: daysAgo(5), status: 'delivered' }],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(3),
  },
  {
    id: 'ref-030',
    firstName: 'Cynthia',
    lastName: 'Roberts',
    email: 'croberts@gmail.com',
    phone: phone(30),
    dateOfBirth: '1962-06-30',
    submittedAt: daysAgo(12),
    source: 'Facebook',
    studyId: 'study-002',
    status: 'attempt_4',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(4),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(12),
    updatedAt: daysAgo(4),
  },
  {
    id: 'ref-081',
    firstName: 'Frank',
    lastName: 'Cooper',
    email: 'fcooper@yahoo.com',
    phone: phone(81),
    dateOfBirth: '1966-03-18',
    submittedAt: daysAgo(13),
    source: 'Google',
    studyId: 'study-001',
    status: 'attempt_4',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(5),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(13),
    updatedAt: daysAgo(5),
  },
  {
    id: 'ref-082',
    firstName: 'Marie',
    lastName: 'Richardson',
    email: 'mrichardson@gmail.com',
    phone: phone(82),
    dateOfBirth: '1964-11-22',
    submittedAt: daysAgo(11),
    source: 'Website',
    studyId: 'study-003',
    status: 'attempt_4',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(3),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(11),
    updatedAt: daysAgo(3),
  },

  // attempt_5 (5 referrals)
  {
    id: 'ref-031',
    firstName: 'Steven',
    lastName: 'Clark',
    email: 'sclark@outlook.com',
    phone: phone(31),
    dateOfBirth: '1959-08-14',
    submittedAt: daysAgo(16),
    source: 'Referral',
    studyId: 'study-004',
    status: 'attempt_5',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(5),
    appointmentDate: null,
    notes: [{ id: 'note-031', referralId: 'ref-031', authorId: 'user-001', authorName: 'Sarah Chen', content: 'Final attempt, marking as unresponsive if no callback', createdAt: daysAgo(5) }],
    messages: [],
    createdAt: daysAgo(16),
    updatedAt: daysAgo(5),
  },
  {
    id: 'ref-032',
    firstName: 'Michelle',
    lastName: 'Lewis',
    email: 'mlewis@gmail.com',
    phone: phone(32),
    dateOfBirth: '1968-01-09',
    submittedAt: daysAgo(15),
    source: 'Google',
    studyId: 'study-001',
    status: 'attempt_5',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(4),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(15),
    updatedAt: daysAgo(4),
  },
  {
    id: 'ref-033',
    firstName: 'Jeffrey',
    lastName: 'Lee',
    email: 'jlee@yahoo.com',
    phone: phone(33),
    dateOfBirth: '1963-04-27',
    submittedAt: daysAgo(17),
    source: 'Facebook',
    studyId: 'study-002',
    status: 'attempt_5',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(6),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(17),
    updatedAt: daysAgo(6),
  },
  {
    id: 'ref-083',
    firstName: 'Catherine',
    lastName: 'Cox',
    email: 'ccox@gmail.com',
    phone: phone(83),
    dateOfBirth: '1961-09-05',
    submittedAt: daysAgo(14),
    source: 'Instagram',
    studyId: 'study-001',
    status: 'attempt_5',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(4),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(4),
  },
  {
    id: 'ref-084',
    firstName: 'Gregory',
    lastName: 'Howard',
    email: 'ghoward@outlook.com',
    phone: phone(84),
    dateOfBirth: '1957-06-19',
    submittedAt: daysAgo(18),
    source: 'Referral',
    studyId: 'study-003',
    status: 'attempt_5',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(7),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(18),
    updatedAt: daysAgo(7),
  },

  // ========================================
  // SCENARIO 4: SMS CONVERSATIONS - sent_sms (8 referrals)
  // ========================================
  {
    id: 'ref-006',
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'mbrown123@gmail.com',
    phone: phone(6),
    dateOfBirth: '1972-01-25',
    submittedAt: daysAgo(5),
    source: 'Website',
    studyId: 'study-004',
    status: 'sent_sms',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(1),
    appointmentDate: null,
    notes: [],
    messages: [
      { id: 'msg-006a', referralId: 'ref-006', direction: 'outbound', content: 'Hi Michael, thanks for your interest in the BEACON kidney study! Is now a good time to chat?', sentAt: daysAgo(2), status: 'delivered' },
      { id: 'msg-006b', referralId: 'ref-006', direction: 'inbound', content: "Hi! I'm interested but have some questions about the time commitment first.", sentAt: daysAgo(1), status: 'read' },
      { id: 'msg-006c', referralId: 'ref-006', direction: 'outbound', content: 'Great question! The study involves monthly visits for 12 months. Each visit is about 2-3 hours.', sentAt: daysAgo(1), status: 'delivered' },
    ],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
  {
    id: 'ref-034',
    firstName: 'Angela',
    lastName: 'Walker',
    email: 'awalker@gmail.com',
    phone: phone(34),
    dateOfBirth: '1969-03-14',
    submittedAt: daysAgo(4),
    source: 'Google',
    studyId: 'study-001',
    status: 'sent_sms',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(1),
    appointmentDate: null,
    notes: [],
    messages: [
      { id: 'msg-034a', referralId: 'ref-034', direction: 'outbound', content: 'Hi Angela! This is Sarah from Orlando Clinical Research. Would love to chat about the diabetes study!', sentAt: daysAgo(2), status: 'delivered' },
      { id: 'msg-034b', referralId: 'ref-034', direction: 'inbound', content: 'Yes! What are the requirements?', sentAt: daysAgo(1), status: 'read' },
    ],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
  },
  {
    id: 'ref-035',
    firstName: 'Nancy',
    lastName: 'Lewis',
    email: 'nlewis@yahoo.com',
    phone: phone(35),
    dateOfBirth: '1966-07-21',
    submittedAt: daysAgo(6),
    source: 'Facebook',
    studyId: 'study-003',
    status: 'sent_sms',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(2),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(6),
    updatedAt: daysAgo(2),
  },
  {
    id: 'ref-036',
    firstName: 'Daniel',
    lastName: 'Hall',
    email: 'dhall@outlook.com',
    phone: phone(36),
    dateOfBirth: '1973-11-03',
    submittedAt: daysAgo(5),
    source: 'Instagram',
    studyId: 'study-001',
    status: 'sent_sms',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(2),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },
  {
    id: 'ref-037',
    firstName: 'Sandra',
    lastName: 'Allen',
    email: 'sallen@gmail.com',
    phone: phone(37),
    dateOfBirth: '1961-05-17',
    submittedAt: daysAgo(4),
    source: 'Website',
    studyId: 'study-002',
    status: 'sent_sms',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(1),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
  },
  {
    id: 'ref-038',
    firstName: 'Richard',
    lastName: 'Young',
    email: 'ryoung@yahoo.com',
    phone: phone(38),
    dateOfBirth: '1968-09-28',
    submittedAt: daysAgo(3),
    source: 'Referral',
    studyId: 'study-001',
    status: 'sent_sms',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(1),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: 'ref-039',
    firstName: 'Donna',
    lastName: 'Hernandez',
    email: 'dhernandez@gmail.com',
    phone: phone(39),
    dateOfBirth: '1970-02-10',
    submittedAt: daysAgo(5),
    source: 'Google',
    studyId: 'study-004',
    status: 'sent_sms',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(2),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },
  {
    id: 'ref-040',
    firstName: 'Carol',
    lastName: 'King',
    email: 'cking@outlook.com',
    phone: phone(40),
    dateOfBirth: '1964-12-25',
    submittedAt: daysAgo(4),
    source: 'Facebook',
    studyId: 'study-001',
    status: 'sent_sms',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(1),
    appointmentDate: null,
    notes: [],
    messages: [],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
  },

  // ========================================
  // SCENARIO 5: APPOINTMENT SCHEDULED (12 referrals)
  // ========================================
  {
    id: 'ref-004',
    firstName: 'Robert',
    lastName: 'Martinez',
    email: 'rmartinez@outlook.com',
    phone: phone(4),
    dateOfBirth: '1970-05-30',
    submittedAt: daysAgo(7),
    source: 'Instagram',
    studyId: 'study-003',
    status: 'appointment_scheduled',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(2),
    appointmentDate: daysFromNow(0),
    notes: [{ id: 'note-004', referralId: 'ref-004', authorId: 'user-002', authorName: 'Mike Rodriguez', content: 'Phone screen scheduled for today at 10am. Patient confirmed.', createdAt: daysAgo(2) }],
    messages: [],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(2),
  },
  {
    id: 'ref-015',
    firstName: 'Angela',
    lastName: 'Foster',
    email: 'afoster@gmail.com',
    phone: phone(15),
    dateOfBirth: '1967-06-12',
    submittedAt: daysAgo(8),
    source: 'Google',
    studyId: 'study-001',
    status: 'appointment_scheduled',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(1),
    appointmentDate: daysFromNow(0),
    notes: [{ id: 'note-015', referralId: 'ref-015', authorId: 'user-001', authorName: 'Sarah Chen', content: 'Rescheduled from yesterday - patient had conflict', createdAt: daysAgo(1) }],
    messages: [],
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },
  {
    id: 'ref-041',
    firstName: 'Ruth',
    lastName: 'Wright',
    email: 'rwright@yahoo.com',
    phone: phone(41),
    dateOfBirth: '1963-08-05',
    submittedAt: daysAgo(10),
    source: 'Facebook',
    studyId: 'study-002',
    status: 'appointment_scheduled',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(3),
    appointmentDate: daysFromNow(1),
    notes: [],
    messages: [],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(3),
  },
  {
    id: 'ref-042',
    firstName: 'Betty',
    lastName: 'Hall',
    email: 'bhall@gmail.com',
    phone: phone(42),
    dateOfBirth: '1958-04-18',
    submittedAt: daysAgo(12),
    source: 'Referral',
    studyId: 'study-002',
    status: 'appointment_scheduled',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(2),
    appointmentDate: daysFromNow(3),
    notes: [{ id: 'note-042', referralId: 'ref-042', authorId: 'user-003', authorName: 'Jennifer Park', content: 'Caregiver will accompany to appointment', createdAt: daysAgo(2) }],
    messages: [],
    createdAt: daysAgo(12),
    updatedAt: daysAgo(2),
  },
  {
    id: 'ref-043',
    firstName: 'Henry',
    lastName: 'Adams',
    email: 'hadams@outlook.com',
    phone: phone(43),
    dateOfBirth: '1965-10-22',
    submittedAt: daysAgo(9),
    source: 'Website',
    studyId: 'study-001',
    status: 'appointment_scheduled',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(2),
    appointmentDate: daysFromNow(2),
    notes: [],
    messages: [],
    createdAt: daysAgo(9),
    updatedAt: daysAgo(2),
  },
  {
    id: 'ref-044',
    firstName: 'Sharon',
    lastName: 'Nelson',
    email: 'snelson@gmail.com',
    phone: phone(44),
    dateOfBirth: '1971-01-30',
    submittedAt: daysAgo(11),
    source: 'Instagram',
    studyId: 'study-003',
    status: 'appointment_scheduled',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(4),
    appointmentDate: daysFromNow(4),
    notes: [],
    messages: [],
    createdAt: daysAgo(11),
    updatedAt: daysAgo(4),
  },
  {
    id: 'ref-045',
    firstName: 'George',
    lastName: 'Allen',
    email: 'gallen@yahoo.com',
    phone: phone(45),
    dateOfBirth: '1960-07-14',
    submittedAt: daysAgo(14),
    source: 'Google',
    studyId: 'study-004',
    status: 'appointment_scheduled',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(3),
    appointmentDate: daysFromNow(3),
    notes: [],
    messages: [],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(3),
  },
  {
    id: 'ref-046',
    firstName: 'Deborah',
    lastName: 'Baker',
    email: 'dbaker@gmail.com',
    phone: phone(46),
    dateOfBirth: '1966-11-08',
    submittedAt: daysAgo(8),
    source: 'Facebook',
    studyId: 'study-001',
    status: 'appointment_scheduled',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(2),
    appointmentDate: daysFromNow(5),
    notes: [],
    messages: [],
    createdAt: daysAgo(8),
    updatedAt: daysAgo(2),
  },
  {
    id: 'ref-047',
    firstName: 'Larry',
    lastName: 'Gonzalez',
    email: 'lgonzalez@outlook.com',
    phone: phone(47),
    dateOfBirth: '1969-03-25',
    submittedAt: daysAgo(10),
    source: 'Referral',
    studyId: 'study-002',
    status: 'appointment_scheduled',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(3),
    appointmentDate: daysFromNow(6),
    notes: [],
    messages: [],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(3),
  },
  {
    id: 'ref-048',
    firstName: 'Dorothy',
    lastName: 'King',
    email: 'dking@gmail.com',
    phone: phone(48),
    dateOfBirth: '1962-09-17',
    submittedAt: daysAgo(9),
    source: 'Website',
    studyId: 'study-001',
    status: 'appointment_scheduled',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(2),
    appointmentDate: daysFromNow(4),
    notes: [],
    messages: [],
    createdAt: daysAgo(9),
    updatedAt: daysAgo(2),
  },
  {
    id: 'ref-085',
    firstName: 'Patrick',
    lastName: 'Ward',
    email: 'pward@yahoo.com',
    phone: phone(85),
    dateOfBirth: '1968-05-11',
    submittedAt: daysAgo(7),
    source: 'Google',
    studyId: 'study-003',
    status: 'appointment_scheduled',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(1),
    appointmentDate: daysFromNow(7),
    notes: [],
    messages: [],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: 'ref-049',
    firstName: 'Brenda',
    lastName: 'Torres',
    email: 'btorres@gmail.com',
    phone: phone(49),
    dateOfBirth: '1973-12-03',
    submittedAt: daysAgo(6),
    source: 'Instagram',
    studyId: 'study-004',
    status: 'appointment_scheduled',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(1),
    appointmentDate: daysFromNow(2),
    notes: [],
    messages: [],
    createdAt: daysAgo(6),
    updatedAt: daysAgo(1),
  },

  // ========================================
  // SCENARIO 6: PHONE SCREEN FAILED (5 referrals)
  // ========================================
  {
    id: 'ref-007',
    firstName: 'Susan',
    lastName: 'Miller',
    email: 'susan.miller@gmail.com',
    phone: phone(7),
    dateOfBirth: '1980-04-18',
    submittedAt: daysAgo(10),
    source: 'Facebook',
    studyId: 'study-001',
    status: 'phone_screen_failed',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(6),
    appointmentDate: null,
    notes: [{ id: 'note-007', referralId: 'ref-007', authorId: 'user-001', authorName: 'Sarah Chen', content: 'A1C too low - 5.9%, study requires >7.0%. Very nice patient, may qualify for future studies.', createdAt: daysAgo(6) }],
    messages: [],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(6),
  },
  {
    id: 'ref-050',
    firstName: 'Virginia',
    lastName: 'Peterson',
    email: 'vpeterson@yahoo.com',
    phone: phone(50),
    dateOfBirth: '1975-06-25',
    submittedAt: daysAgo(12),
    source: 'Google',
    studyId: 'study-001',
    status: 'phone_screen_failed',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(8),
    appointmentDate: null,
    notes: [{ id: 'note-050', referralId: 'ref-050', authorId: 'user-002', authorName: 'Mike Rodriguez', content: 'Currently on exclusionary medication (Jardiance)', createdAt: daysAgo(8) }],
    messages: [],
    createdAt: daysAgo(12),
    updatedAt: daysAgo(8),
  },
  {
    id: 'ref-051',
    firstName: 'Eugene',
    lastName: 'Campbell',
    email: 'ecampbell@outlook.com',
    phone: phone(51),
    dateOfBirth: '1970-02-14',
    submittedAt: daysAgo(15),
    source: 'Referral',
    studyId: 'study-003',
    status: 'phone_screen_failed',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(10),
    appointmentDate: null,
    notes: [{ id: 'note-051', referralId: 'ref-051', authorId: 'user-003', authorName: 'Jennifer Park', content: 'BMI 24, study requires >30', createdAt: daysAgo(10) }],
    messages: [],
    createdAt: daysAgo(15),
    updatedAt: daysAgo(10),
  },
  {
    id: 'ref-052',
    firstName: 'Paul',
    lastName: 'Scott',
    email: 'pscott@gmail.com',
    phone: phone(52),
    dateOfBirth: '1963-09-08',
    submittedAt: daysAgo(11),
    source: 'Facebook',
    studyId: 'study-002',
    status: 'phone_screen_failed',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(7),
    appointmentDate: null,
    notes: [{ id: 'note-052', referralId: 'ref-052', authorId: 'user-001', authorName: 'Sarah Chen', content: 'Age outside study range (requires 55-70)', createdAt: daysAgo(7) }],
    messages: [],
    createdAt: daysAgo(11),
    updatedAt: daysAgo(7),
  },
  {
    id: 'ref-053',
    firstName: 'Joyce',
    lastName: 'Evans',
    email: 'jevans@yahoo.com',
    phone: phone(53),
    dateOfBirth: '1968-11-20',
    submittedAt: daysAgo(13),
    source: 'Website',
    studyId: 'study-004',
    status: 'phone_screen_failed',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(9),
    appointmentDate: null,
    notes: [{ id: 'note-053', referralId: 'ref-053', authorId: 'user-002', authorName: 'Mike Rodriguez', content: 'eGFR too high, does not meet CKD criteria', createdAt: daysAgo(9) }],
    messages: [],
    createdAt: daysAgo(13),
    updatedAt: daysAgo(9),
  },

  // ========================================
  // SCENARIO 7: NOT INTERESTED (6 referrals)
  // ========================================
  {
    id: 'ref-008',
    firstName: 'David',
    lastName: 'Wilson',
    email: 'dwilson@hotmail.com',
    phone: phone(8),
    dateOfBirth: '1958-12-03',
    submittedAt: daysAgo(8),
    source: 'Referral',
    studyId: 'study-002',
    status: 'not_interested',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(5),
    appointmentDate: null,
    notes: [{ id: 'note-008', referralId: 'ref-008', authorId: 'user-002', authorName: 'Mike Rodriguez', content: 'Spouse not supportive of clinical trial participation. Patient said maybe in the future.', createdAt: daysAgo(5) }],
    messages: [],
    createdAt: daysAgo(8),
    updatedAt: daysAgo(5),
  },
  {
    id: 'ref-054',
    firstName: 'Helen',
    lastName: 'Edwards',
    email: 'hedwards@gmail.com',
    phone: phone(54),
    dateOfBirth: '1965-03-28',
    submittedAt: daysAgo(9),
    source: 'Google',
    studyId: 'study-001',
    status: 'not_interested',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(6),
    appointmentDate: null,
    notes: [{ id: 'note-054', referralId: 'ref-054', authorId: 'user-001', authorName: 'Sarah Chen', content: 'Concerned about time commitment, works full time', createdAt: daysAgo(6) }],
    messages: [],
    createdAt: daysAgo(9),
    updatedAt: daysAgo(6),
  },
  {
    id: 'ref-055',
    firstName: 'Ruth',
    lastName: 'Green',
    email: 'rgreen@yahoo.com',
    phone: phone(55),
    dateOfBirth: '1960-07-15',
    submittedAt: daysAgo(11),
    source: 'Facebook',
    studyId: 'study-003',
    status: 'not_interested',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(7),
    appointmentDate: null,
    notes: [{ id: 'note-055', referralId: 'ref-055', authorId: 'user-003', authorName: 'Jennifer Park', content: 'Decided to try lifestyle changes first', createdAt: daysAgo(7) }],
    messages: [],
    createdAt: daysAgo(11),
    updatedAt: daysAgo(7),
  },
  {
    id: 'ref-056',
    firstName: 'Frank',
    lastName: 'Collins',
    email: 'fcollins@outlook.com',
    phone: phone(56),
    dateOfBirth: '1967-10-09',
    submittedAt: daysAgo(10),
    source: 'Instagram',
    studyId: 'study-001',
    status: 'not_interested',
    assignedTo: 'user-002',
    lastContactedAt: daysAgo(6),
    appointmentDate: null,
    notes: [{ id: 'note-056', referralId: 'ref-056', authorId: 'user-002', authorName: 'Mike Rodriguez', content: 'Found another study closer to home', createdAt: daysAgo(6) }],
    messages: [],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(6),
  },
  {
    id: 'ref-057',
    firstName: 'Anna',
    lastName: 'Stewart',
    email: 'astewart@gmail.com',
    phone: phone(57),
    dateOfBirth: '1972-05-22',
    submittedAt: daysAgo(7),
    source: 'Website',
    studyId: 'study-002',
    status: 'not_interested',
    assignedTo: 'user-001',
    lastContactedAt: daysAgo(4),
    appointmentDate: null,
    notes: [{ id: 'note-057', referralId: 'ref-057', authorId: 'user-001', authorName: 'Sarah Chen', content: 'Primary care physician advised against participation', createdAt: daysAgo(4) }],
    messages: [],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(4),
  },
  {
    id: 'ref-058',
    firstName: 'Raymond',
    lastName: 'Sanchez',
    email: 'rsanchez@yahoo.com',
    phone: phone(58),
    dateOfBirth: '1959-01-14',
    submittedAt: daysAgo(12),
    source: 'Referral',
    studyId: 'study-004',
    status: 'not_interested',
    assignedTo: 'user-003',
    lastContactedAt: daysAgo(8),
    appointmentDate: null,
    notes: [{ id: 'note-058', referralId: 'ref-058', authorId: 'user-003', authorName: 'Jennifer Park', content: 'Insurance concerns - worried about coverage gaps', createdAt: daysAgo(8) }],
    messages: [],
    createdAt: daysAgo(12),
    updatedAt: daysAgo(8),
  },
];

// Helper functions
export function getReferralById(id: string): Referral | undefined {
  return mockReferrals.find((referral) => referral.id === id);
}

export function getReferralsByStatus(status: Referral['status']): Referral[] {
  return mockReferrals.filter((referral) => referral.status === status);
}

export function getReferralsByStudy(studyId: string): Referral[] {
  return mockReferrals.filter((referral) => referral.studyId === studyId);
}

export function getReferralsByAssignee(userId: string | null): Referral[] {
  return mockReferrals.filter((referral) => referral.assignedTo === userId);
}

export function getNewReferralsCount(): number {
  return mockReferrals.filter((referral) => referral.status === 'new').length;
}

export function getReferralFullName(referral: Referral): string {
  return `${referral.firstName} ${referral.lastName}`;
}

export function getSignedICFCount(): number {
  return mockReferrals.filter((referral) => referral.status === 'signed_icf').length;
}

export function getActiveReferralsCount(): number {
  const inactiveStatuses = ['phone_screen_failed', 'not_interested', 'signed_icf'];
  return mockReferrals.filter((referral) => !inactiveStatuses.includes(referral.status)).length;
}

export function getConversionRate(): number {
  const signedCount = getSignedICFCount();
  const total = mockReferrals.length;
  return total > 0 ? Math.round((signedCount / total) * 100) : 0;
}

export function getOverdueReferrals(daysSinceUpdate: number = 2): Referral[] {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - daysSinceUpdate);

  const activeStatuses = ['new', 'attempt_1', 'attempt_2', 'attempt_3', 'attempt_4', 'attempt_5', 'sent_sms'];

  return mockReferrals.filter((referral) => {
    if (!activeStatuses.includes(referral.status)) return false;
    const updated = new Date(referral.updatedAt);
    return updated < cutoff;
  });
}
